# 1 "framework/protocol/linkkit/iotkit/iotkit-system/src/id2_guider.c"
# 1 "/home/stone/Documents/Ali_IOT//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "framework/protocol/linkkit/iotkit/iotkit-system/src/id2_guider.c"
